"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const cache = require("./utils/cache.js");
const is = require("./utils/is.js");
exports.WebCache = cache.WebCache;
exports.is = is.is;
exports.isArray = is.isArray;
exports.isBoolean = is.isBoolean;
exports.isClient = is.isClient;
exports.isDate = is.isDate;
exports.isDef = is.isDef;
exports.isElement = is.isElement;
exports.isEmpty = is.isEmpty;
exports.isFunction = is.isFunction;
exports.isLink = is.isLink;
exports.isMap = is.isMap;
exports.isNull = is.isNull;
exports.isNullAndUnDef = is.isNullAndUnDef;
exports.isNullOrUnDef = is.isNullOrUnDef;
exports.isNumber = is.isNumber;
exports.isObject = is.isObject;
exports.isPromise = is.isPromise;
exports.isRegExp = is.isRegExp;
exports.isServer = is.isServer;
exports.isString = is.isString;
exports.isUnDef = is.isUnDef;
exports.isWindow = is.isWindow;
